In [1]:
training_data = [[170, 65],
                 [155, 50],
                 [150, 45],
                 [175, 70],
                 [165, 55]]

print(training_data)

[[170, 65], [155, 50], [150, 45], [175, 70], [165, 55]]


In [3]:
import sympy as sym

a = sym.Symbol('a')
b = sym.Symbol('b')

Residual = 0

for i in range(len(training_data)):
    Residual += (training_data[i][0]*a + b - training_data[i][1]) **2




In [4]:
Residual

(150*a + b - 45)**2 + (155*a + b - 50)**2 + (165*a + b - 55)**2 + (170*a + b - 65)**2 + (175*a + b - 70)**2

In [5]:
R_Diff_a = sym.diff(Residual, a)
R_Diff_a

266550*a + 1630*b - 93750

In [6]:
R_Diff_b = sym.diff(Residual, b)
R_Diff_b

1630*a + 10*b - 570

In [7]:
import numpy as np

A = [[266550, 1630],
     [1630, 10]]

B = [93750, 570]

inv_A = np.linalg.inv(A)
X = np.dot(inv_A, B)



print(X)


[   0.97674419 -102.20930233]


In [9]:
import numpy as np

A = [[170, 1],
     [155, 1],
     [150, 1],
     [175, 1],
     [165, 1]]

Y = [[65], [50], [45], [70], [55]]



At = np.transpose(A)

print(At)


[[170 155 150 175 165]
 [  1   1   1   1   1]]


In [10]:

AtA = np.dot(At, A)
AtY = np.dot(At, Y)

print(AtA)
print(AtY)
inv_AtA = np.linalg.inv(AtA)
X = np.dot(inv_AtA, AtY)

print(X)



[[133275    815]
 [   815      5]]
[[46875]
 [  285]]
[[   0.97674419]
 [-102.20930233]]


In [11]:
# training data
arm = [40, 30, 20, 70, 60]
leg = [30, 80, 70, 40, 20]
gen = [1, -1, -1, 1, 1]
print(arm, leg, gen)

# differential

import sympy as sym

a = sym.Symbol('a')
b = sym.Symbol('b')
c = sym.Symbol('c')
R = 0


[40, 30, 20, 70, 60] [30, 80, 70, 40, 20] [1, -1, -1, 1, 1]


In [12]:
# Residual
for i in range(0,5):
    R+=(arm[i]*a+leg[i]*b+c-gen[i])**2

R_a=sym.diff(R,a)
R_b=sym.diff(R,b)
R_c=sym.diff(R,c)
print("Result of differentiating with respect to a:", R_a, "= 0")
print("Result of differentiating with respect to b:", R_b, "= 0")
print("Result of differentiating with respect to c:", R_c, "= 0")


Result of differentiating with respect to a: 22800*a + 18000*b + 440*c - 240 = 0
Result of differentiating with respect to b: 18000*a + 28400*b + 480*c + 120 = 0
Result of differentiating with respect to c: 440*a + 480*b + 10*c - 2 = 0


In [13]:


import numpy as np
A=[[22800,18000,440],[18000,28400,480],[440,480,10]]
B=[240,-120,2]
inv_A=np.linalg.inv(A)
result=np.dot(inv_A,B)
print("a=",result[0]," b=",result[1]," c=",result[2])
a=result[0]
b=result[1]
c=result[2]


a= 0.01617647058823525  b= -0.030882352941176514  c= 0.9705882352941213


In [14]:


import numpy as np

A = [[40, 30, 1],
     [30, 80, 1],
     [20, 70, 1],
     [70, 40, 1],
     [60, 20, 1]]

Z = [[1], [-1], [-1], [1], [1]]

At = np.transpose(A)
print(At)

[[40 30 20 70 60]
 [30 80 70 40 20]
 [ 1  1  1  1  1]]


In [15]:
AtA = np.dot(At, A)
AtZ = np.dot(At, Z)

print(AtA)
print(AtZ)
inv_AtA = np.linalg.inv(AtA)
X = np.dot(inv_AtA, AtZ)
print(X)


[[11400  9000   220]
 [ 9000 14200   240]
 [  220   240     5]]
[[120]
 [-60]
 [  1]]
[[ 0.01617647]
 [-0.03088235]
 [ 0.97058824]]
